services:
  ftsrelay:
    image: ftsrelay
    container_name: ftsrelay
    hostname: ftsrelay
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3332:3000"
    environment:
      - NODE_ENV=production
    # volumes:
    #   - .:/app
    restart: unless-stopped
    networks:
      - nostr-daemon

networks:
  nostr-daemon:
    external: true
