services:
  albyhub:
    platform: linux/amd64
    container_name: albyhub
    image: alby
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    environment:
      - WORK_DIR=/data/albyhub
      - LOG_EVENTS=true