version: '3.9'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    volumes:
      - ./getcerts.Caddyfile:/etc/caddy/Caddyfile:ro
      - ./getCertsSites/:/usr/share/caddy/sites
      - ./caddy/data:/data
      - ./caddy/config:/config
    environment:
      - TZ=EST

networks:
  nostr-daemon:
    external: true
