version: '3.9'

services:
  ssh-server:
    image: ssh-test
    container_name: ssh-test
    hostname: ssh-test
    ports:
      - "2222:22"
    restart: unless-stopped
    volumes:
      - ./id_rsa.pub:/root/.ssh/authorized_keys:ro
      - ./caddy/sites:/usr/share/caddy/sites
    networks:
      - nostr-daemon
  caddy:
    image: caddy:latest
    container_name: caddy_server
    restart: unless-stopped
    ports:
      - "8090:80"    # HTTP
      - "4443:443"   # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/sites:/usr/share/caddy/sites
      - ./caddy/data:/data
      - ./caddy/config:/config
    environment:
      - TZ=EST

networks:
  nostr-daemon:
    external: true
