services:
  lnd:
    image: lnd
    hostname: lnd
    ports:
      - 10009:10009
    environment:
      - RPCUSER=devuser
      - RPCPASS=devpass
      - RPCHOST=btcd-simnet
      - RPCCRTPATH=/rpc/rpc.cert
      - NETWORK=simnet
      - DEFAULT_NETWORK=simnet
      - CHAIN=bitcoin
      - BACKEND=btcd
      - LND_DEBUG
      # - EXTERNAL_IP_ADDRESS
    volumes:
    #  - ./start-lnd.sh:/lnd/start-lnd.sh
      - ./rpc:/rpc
    # - lnd:/root/.lnd
    entrypoint: ["/lnd/start-lnd.sh"]
    networks:
      - simnet

networks:
  simnet:
    external: true
