services:
  lnd:
    image: lnd
    hostname: lnd-mainnet
    container_name: lnd-mainnet
    ports:
      - 10009:10009
    environment:
      - RPCUSER
      - RPCPASS
      - RPCHOST
      - RPCCRTPATH=/rpc/btcd.cert
      - NETWORK=testnet
      - DEFAULT_NETWORK=testnet
      - CHAIN=bitcoin
      - BACKEND=btcd
      - LND_DEBUG
      # - EXTERNAL_IP_ADDRESS
    volumes:
      - ./lnd.mainnet.conf:/root/.lnd/lnd.conf
      # - ./start-lnd-testnet.sh:/lnd/start-lnd.sh
      - ./data/mainnet/rpc/btcd.cert:/btcd.cert
      - ./data/mainnet-lnd/node001/:/root/.lnd
    # entrypoint: ["/lnd/start-lnd.sh"]
    command: [
      "lnd", 
      # "--bitcoin.mainnet",
      # "--debuglevel=debug", 
      # "--btcd.rpcuser=USER", 
      # "--btcd.rpcpass=PASS",
      # "--btcd.rpccert=/rpc/btcd.cert",
      # "--btcd.rpchost=btcd-testnet:18335",
      # "--rpclisten=0.0.0.0:10009",
      # "--externalip=127.0.0.1"
    ]
    extra_hosts:
      - "btcd-mainnet:$IP_ADDRESS_OF_BITCOIN_NODE_GOES_HERE"
    networks:
      - mainnet

networks:
  mainnet:
    external: true
