services:
  lnd2:
    image: lnd
    hostname: lnd-testnet2
    container_name: lnd-testnet2
    ports:
      - 11009:10009
    environment:
      - RPCUSER
      - RPCPASS
      - RPCHOST
      - RPCCRTPATH=/rpc/rpc.cert
      - NETWORK=testnet
      - DEFAULT_NETWORK=testnet
      - CHAIN=bitcoin
      - BACKEND=btcd
      - LND_DEBUG
      # - EXTERNAL_IP_ADDRESS
    volumes:
      - ./testnet/rpc:/rpc
      - ./testnet/wallet002/:/root/.lnd
    # entrypoint: ["/lnd/start-lnd.sh"]
    command: [
      "lnd", 
      "--bitcoin.active",
      "--bitcoin.testnet",
      "--debuglevel=debug", 
      "--btcd.rpcuser=USER", 
      "--btcd.rpcpass=PASS",
      "--btcd.rpccert=/rpc/rpc.cert",
      "--btcd.rpchost=btcd-testnet:18335",
      "--externalip=127.0.0.1"
    ]
    extra_hosts:
      - "btcd-testnet:192.168.7.220"
    networks:
      - testnet

networks:
  testnet:
    external: true
