services:
  strfry:
    image: strfry
    container_name: strfry
    hostname: strfry
    restart: always
    volumes:
      - ./strfry.conf:/etc/strfry.conf
      - ./data/strfry-db:/app/strfry-db
    ports:
      - "7777:7777"
    networks:
      - nostr-daemon

networks:
  nostr-daemon:
    external: true

