services:
  lnbits-testnet:
    container_name: lnbits-testnet
    hostname: lnbits-testnet
    image: lnbits
    restart: unless-stopped
    ports:
      - 5000:5000
    env_file:
      - .env.testnet
    volumes:
      - ./data:/data
      - ./data-simnet/rpc:/rpc
      - ./lnbits.macaroon:/lnbits.macaroon
      - ./tls.cert:/lnd.cert
    # command: [ "bash", "/start-btcd.sh" ]
    extra_hosts:
      - "bob.testnostr.com:10.100.100.11"
    networks:
      testnet

networks:
  testnet:
    external: true
