version: '3.8'

services:
  khatru-relay:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3334:3334"
    volumes:
      - ./nostr.sqlite:/app/nostr.sqlite
    restart: unless-stopped
    networks:
      - nostr-daemon

networks:
  nostr-daemon:
    external: true
