version: '3.1'

services:

  db:
    image: paradedb/paradedb:latest
    container_name: ditto-postgres
    hostname: ditto-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: ditto
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ditto:
    image: ditto
    container_name: ditto
    hostname: ditto
    restart: always
    environment:
      # Use https://nostrtool.com/ to generate a new one
      DITTO_NSEC: "nsec1ssllvcypa7v3438m5fc7l7ncl6yxyfte0hpuhefljhg9skd6aams72tcyc"
      # psql postgres://postgres:postgres@127.0.0.1:5432/ditto
      DATABASE_URL: "postgres://postgres:postgres@ditto-postgres:5432/ditto"
      LOCAL_DOMAIN: "https://social.mememaps.net"
      PORT: "4036"
    ports:
      - 4036:4036

volumes:
  postgres_data:

networks:
  nostr-daemon:
    external: true
