services:
  sqlitenode:
    image: sqlitenode
    container_name: sqlitenode
    hostname: sqlitenode
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4869:4869"
    # volumes:
    #   - ./nostr.sqlite:/app/nostr.sqlite
    restart: unless-stopped
    networks:
      - nostr-daemon

networks:
  nostr-daemon:
    external: true
