services:
  lnd:
    image: lnd
    hostname: lnd-testnet
    container_name: lnd-testnet
    env_file: # IDK why this doesn't want to work
      - .env.testnet
    ports:
      - 10009:10009
    environment:
      - RPCUSER
      - RPCPASS
      - RPCHOST
      - RPCCRTPATH=/rpc/btcd.cert
      - NETWORK=testnet
      - DEFAULT_NETWORK=testnet
      - CHAIN=bitcoin
      - BACKEND=btcd
      - LND_DEBUG
      # - EXTERNAL_IP_ADDRESS
    volumes:
      - ./lnd.testnet.conf:/root/.lnd/lnd.conf
      - ./start-lnd-testnet.sh:/lnd/start-lnd.sh
      # - ${PATH_FOR_DOCKER_VOLUMES}/testnet/certs:/certs
      # - ${PATH_FOR_DOCKER_VOLUMES}/testnet-lnd/node001/:/root/.lnd
      - /mnt/docker-volumes/testnet/certs:/certs
      - /mnt/docker-volumes/testnet-lnd/node001/:/root/.lnd
    # entrypoint: ["/lnd/start-lnd.sh"]
    command: [
      "lnd",
      "--bitcoin.testnet",
      "--bitcoin.node=neutrino",
      "--neutrino.connect=192.168.7.220:18333"
      # "--debuglevel=debug", 
      # "--btcd.rpcuser=USER", 
      # "--btcd.rpcpass=PASS",
      # "--btcd.rpccert=/rpc/btcd.cert",
      # "--btcd.rpchost=btcd-testnet:18335",
      # "--rpclisten=0.0.0.0:10009",
      # "--externalip=127.0.0.1"
    ]
    # extra_hosts:
    #   - "btcd-testnet:$BITCOIN_NODE_IP_ADDRESS"
    networks:
      - testnet

networks:
  testnet:
    external: true
