services:
  lnd2:
    image: lnd
    hostname: lnd-testnet2
    container_name: lnd-testnet2
    ports:
      - 11009:10009
    environment:
      - RPCUSER
      - RPCPASS
      - RPCHOST
      - RPCCRTPATH=/rpc/rpc.cert
      - NETWORK=testnet
      - DEFAULT_NETWORK=testnet
      - CHAIN=bitcoin
      - BACKEND=btcd
      - LND_DEBUG
      # - EXTERNAL_IP_ADDRESS
    volumes:
      - ./lnd.testnet.conf:/root/.lnd/lnd.conf
      - ./start-lnd-testnet.sh:/lnd/start-lnd.sh
      - ${PATH_FOR_DOCKER_VOLUMES}/testnet/rpc:/rpc
      - ${PATH_FOR_DOCKER_VOLUMES}/testnet-lnd/node001/:/root/.lnd
    # entrypoint: ["/lnd/start-lnd.sh"]
    command: [
      "lnd", 
      "--bitcoin.active",
      "--bitcoin.testnet",
      "--debuglevel=debug", 
      "--btcd.rpcuser=${BITCOIN_NODE_USERNAME}", 
      "--btcd.rpcpass=${BITCOIN_NODE_PASSWORD}",
      "--btcd.rpccert=/rpc/rpc.cert",
      "--btcd.rpchost=${BITCOIN_NODE_HOSTNAME}:${BITCOIN_NODE_RPC_PORT}",
      "--externalip=127.0.0.1"
    ]
    # extra_hosts:
    #   - "btcd-testnet:192.168.7.220"
    networks:
      - testnet

networks:
  testnet:
    external: true
