services:
  nostr-relay:
    image: nostr-relay
    container_name: nostr-relay
    hostname: nostr-relay
    ports:
      - "6969:6969"
    command: nostr-relay -c /config/config.yaml serve
    volumes:
      - "./data/nostr-relay/app:/app"
      - "./nostr-relay-config.yml:/config/config.yaml"
#     networks:
#       - nostr-daemon

# networks:
#   nostr-daemon:
#     external: true
