services:
  btcd-testnet:
    container_name: btcd-testnet
    hostname: btcd-testnet
    image: btcd
    restart: unless-stopped
    volumes:
      - ./data:/root/.btcd
    ports:
      - 18333:18333
      - 18334:18334
      - 18335:18335
    command: [
        "--testnet",
        "--rpcuser=USER",
        "--rpcpass=PASS",
        "--rpclisten=0.0.0.0:18335",
        "--txindex"
    ]
